"""
Normalized Windows Event Parser
================================
This module transforms raw Windows Event Log XML (EVTX export or pywin32 rendered XML)
into a normalized Python dictionary schema compatible with SentinelTwin's event ingestion pipeline.

Supported Security & Audit Event IDs:
  - 4624: Successful Logon (extracts user, source IP, logon type)
  - 4625: Failed Logon (extracts attempted username, source IP, failure code)
  - 4688: Process Creation (extracts process executable, parent process, command line arguments)
"""
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
import logging

logger = logging.getLogger(__name__)

def parse_windows_event_xml(xml_content: str) -> dict:
    """
    Parses a raw Windows Event Log XML string into a structured, normalized dictionary.

    Windows Event XML structure:
      <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
        <System>
          <EventID>4624</EventID>
          <EventRecordID>12345</EventRecordID>
          <Channel>Security</Channel>
          <Computer>DESKTOP-ABC</Computer>
          <TimeCreated SystemTime="2026-09-21T10:00:00.000Z" />
        </System>
        <EventData>
          <Data Name="TargetUserName">SYSTEM</Data>
          <Data Name="IpAddress">192.168.1.50</Data>
          ...
        </EventData>
      </Event>

    Args:
        xml_content (str): The raw XML string rendered from win32evtlog.

    Returns:
        dict: Normalized event record with standardized fields, or empty dict if parsing fails.
    """
    try:
        # Parse XML string into an ElementTree node hierarchy
        root = ET.fromstring(xml_content)
    except Exception as e:
        logger.error(f"Failed to parse XML: {e}")
        return {}

    # Windows Event Log XML uses a standard XML namespace
    ns = {"e": "http://schemas.microsoft.com/win/2004/08/events/event"}

    # --- 1. Extract Header Metadata from <System> ---
    system = root.find("e:System", ns)
    if system is None:
        return {}

    # Event ID (e.g., 4624, 4625, 4688)
    event_id_elem = system.find("e:EventID", ns)
    event_id = int(event_id_elem.text) if event_id_elem is not None and event_id_elem.text else 0

    # Sequential record index in the local Windows Event Log channel
    record_id_elem = system.find("e:EventRecordID", ns)
    record_id = int(record_id_elem.text) if record_id_elem is not None and record_id_elem.text else 0

    # Logging channel (typically 'Security' or 'Microsoft-Windows-Sysmon/Operational')
    channel_elem = system.find("e:Channel", ns)
    channel = channel_elem.text if channel_elem is not None and channel_elem.text else "Security"

    # Computer / Hostname of the generating system
    computer_elem = system.find("e:Computer", ns)
    computer = computer_elem.text if computer_elem is not None and computer_elem.text else "localhost"

    # Creation timestamp generated by the Windows kernel
    time_created = system.find("e:TimeCreated", ns)
    if time_created is not None and "SystemTime" in time_created.attrib:
        raw_ts = time_created.attrib["SystemTime"]
        # Ensure UTC timezone indicator if missing from Windows local time string
        if raw_ts and not raw_ts.endswith("Z") and "+" not in raw_ts[-6:] and "-" not in raw_ts[-6:]:
            event_timestamp = raw_ts + "Z"
        else:
            event_timestamp = raw_ts
    else:
        # Fallback to current UTC time if SystemTime attribute is absent
        event_timestamp = datetime.now(timezone.utc).isoformat()

    # --- 2. Extract Event Specific Attributes from <EventData> ---
    event_data = {}
    ed = root.find("e:EventData", ns)
    if ed is not None:
        # Each data item in Windows EventData is formatted as: <Data Name="Key">Value</Data>
        for data in ed.findall("e:Data", ns):
            name = data.attrib.get("Name")
            val = data.text or ""
            if name:
                event_data[name] = val

    # --- 3. Construct Normalized SentinelTwin Schema ---
    normalized = {
        "event_id": event_id,
        "record_id": record_id,
        "channel": channel,
        "device_id": f"dev-{computer.replace('.', '-')}",  # Standardized device identifier
        "computer": computer,
        "event_timestamp": event_timestamp,
        "user": None,
        "process_name": None,
        "parent_process": None,
        "command_line": None,
        "source_ip": None,
        "logon_type": None,
        "metadata": event_data  # Preserves all raw key-value pairs for forensics
    }

    # --- 4. Event-Specific Field Mapping ---
    # Event ID 4624: Successful Logon
    if event_id == 4624:
        normalized["user"] = event_data.get("TargetUserName")
        normalized["source_ip"] = event_data.get("IpAddress")
        normalized["logon_type"] = event_data.get("LogonType")  # e.g., 2=Interactive, 3=Network, 10=RDP

    # Event ID 4625: Failed Logon
    elif event_id == 4625:
        normalized["user"] = event_data.get("TargetUserName")
        normalized["source_ip"] = event_data.get("IpAddress")
        normalized["logon_type"] = event_data.get("LogonType")

    # Event ID 4688: Process Creation (Command Execution)
    elif event_id == 4688:
        normalized["user"] = event_data.get("SubjectUserName")
        normalized["process_name"] = event_data.get("NewProcessName")
        normalized["parent_process"] = event_data.get("ParentProcessName")
        normalized["command_line"] = event_data.get("CommandLine")

    return normalized